language: c
os: linux
dist: trusty
sudo: required
env:
  global:
  - secure: tD/M9SO0SMisa/oKHn+1QtoB1yE5MnfWBecrJvc/fsZ7DZJ/hjj0wnt7OrNbi3nIwByMvFdnrcAwfv8JOTipSf25FN7REhlVRtyaA14QJdv2eo9Zu6Luno7F+JWn7/6MVXdK4HqwJJfiUg4qmwJX2G3qDZl+/J6I+GUt8ItEkPW/4mmB8l/i5+YE7CNxu8kQa17KJOwfRepN9RL586OxfgvR0bfSRns4/We239hLQpAPdOHBKy5MPf+diXnBtQ0MJzOhLz0jFrnrKwZhwrGpKH5bmaQp2HGL21ye4n5bASY93PQ05EgQACoWm6ECE2+fU1QqAJTn3+dYBMtBG+NESTHF5TaATf+ge181bZGedExtKlbyJeX0EzhF9U+sL+s3sxxUX7aHH3pkqqa1n6U+dWETJhRfvX7q6htNaRrPEL1f2o1W4hyWW6Aa5J2JMqRRf0MvwhWOZi5KbUx5qHLxFpnTZ0PkqfP2glsNqakKbMusOikKqKWZVesESgA4Z0JNeQBRV0mAccuaOlG4jjZcUhkLlvH7sA324XK1Kb+Twh6rScR3KtTNmOYEBt2DvEjsCy9ddWBIPWisjIpJVHRBvlX0wHqrPY0eZGtbR1MH3hLcvJ7MRTs0l1O5ExQtFnWwfTTKbvYigsz+L+glrDSVnJMDBYKfnI/AvXWub2tTLMI=
  matrix:
  - LIBC=glibc
    ARCH=x86_64
  - LIBC=glibc
    ARCH=i686
  - LIBC=musl
    ARCH=x86_64
  - LIBC=musl
    ARCH=i686
matrix:
  fast_finish: true
  allow_failures:
  - env: LIBC=musl ARCH=i686
    language: c
addons:
  apt:
    packages:
    - gcc-multilib
script:
- if test $ARCH = i686; then export MUSL_TARGET=i686-unknown-linux; fi
- if test $LIBC = musl; then CC=gcc AR=ar RANLIB=ranlib make -j4 musl && export DEFCONFIG=defconfig.musl CC=musl-gcc; fi
- if test $ARCH = i686; then export CC="$CC -m32" CFLAGS=-m32 LDFLAGS=-m32; fi
- make -j4
- cp build/busybox busybox-$LIBC-$ARCH
- cp build/ssl_helper ssl_helper-$LIBC-$ARCH
deploy:
  provider: releases
  file:
  - busybox-$LIBC-$ARCH
  - ssl_helper-$LIBC-$ARCH
  api_key: "$GH_TOKEN"
  on:
    tags: true
    all_branches: true
